experimental_monorepo_root = true

[tools]
prek = "latest"

[tasks.setup]
depends = [
  "//anki-extract-kanji:setup",
  "//wanikani-apprentice:setup",
  "//wanikani-burnt-kanji-to-anki:setup",
]
run = [
  "prek install",
]

[tasks.test]
depends = [
  "//anki-extract-kanji:test",
  "//wanikani-apprentice:test",
  "//wanikani-burnt-kanji-to-anki:test",
]

[tasks.lint]
run = "prek run --all-files"
