experimental_monorepo_root = true

[env]
UV_PREVIEW_FEATURES = "add-bounds"

[monorepo]
config_roots = [
  "anki-extract-kanji",
  "wanikani-apprentice",
  "wanikani-burnt-kanji-to-anki",
]

[tools]
prek = "latest"

[tasks.setup]
depends = "//...:setup"
run = [
  "prek install",
]

[tasks.test]
depends = "//...:test"

[tasks.lint]
run = "prek run --all-files"
