experimental_monorepo_root = true

[tools]
pre-commit = "latest"

[tasks.setup]
depends = [
  "//anki-extract-kanji:setup",
  "//wanikani-apprentice:setup",
  "//wanikani-burnt-kanji-to-anki:setup",
]
run = [
  "mise install",
  "pre-commit install",
]

[tasks.test]
depends = [
  "//anki-extract-kanji:test",
  "//wanikani-apprentice:test",
  "//wanikani-burnt-kanji-to-anki:test",
]
