[tools]
python = "3.14.0"

[env]
_.python.venv = { path = ".venv", create = true }

[hooks]
postinstall = [
  "uv sync --active",
]

[tasks.setup]
run = "mise install"

[tasks.test]
depends = [":setup"]
run = "tox"
